In [1]:
import pandas as pd
import glob, os
import warnings 
warnings.filterwarnings('ignore')
pd.set_option('display.max_colwidth', 700)

In [ ]:
path = r'../data' # r'C:\big20\ml_dev\chap08\topics' r 쓴이유는 안에 // 가 ecape문자가 되기 때문이다!!
# path로 지정한 디렉터리 밑에 있는 모든 .data 파일들의 파일명을 리스트로 취합
all_files = glob.glob(os.path.join(path, "*.data"))    # 많이 나올 수 있다!!!
all_files # 파일명이 레이블이다! 제품명들어 있음

['./topics\\accuracy_garmin_nuvi_255W_gps.txt.data',
 './topics\\bathroom_bestwestern_hotel_sfo.txt.data',
 './topics\\battery-life_amazon_kindle.txt.data',
 './topics\\battery-life_ipod_nano_8gb.txt.data',
 './topics\\battery-life_netbook_1005ha.txt.data',
 './topics\\buttons_amazon_kindle.txt.data',
 './topics\\comfort_honda_accord_2008.txt.data',
 './topics\\comfort_toyota_camry_2007.txt.data',
 './topics\\directions_garmin_nuvi_255W_gps.txt.data',
 './topics\\display_garmin_nuvi_255W_gps.txt.data',
 './topics\\eyesight-issues_amazon_kindle.txt.data',
 './topics\\features_windows7.txt.data',
 './topics\\fonts_amazon_kindle.txt.data',
 './topics\\food_holiday_inn_london.txt.data',
 './topics\\food_swissotel_chicago.txt.data',
 './topics\\free_bestwestern_hotel_sfo.txt.data',
 './topics\\gas_mileage_toyota_camry_2007.txt.data',
 './topics\\interior_honda_accord_2008.txt.data',
 './topics\\interior_toyota_camry_2007.txt.data',
 './topics\\keyboard_netbook_1005ha.txt.data',
 './topics\\location_bestwestern_hotel_sfo.txt.data',
 './topics\\location_holiday_inn_london.txt.data',
 './topics\\mileage_honda_accord_2008.txt.data',
 './topics\\navigation_amazon_kindle.txt.data',
 './topics\\parking_bestwestern_hotel_sfo.txt.data',
 './topics\\performance_honda_accord_2008.txt.data',
 './topics\\performance_netbook_1005ha.txt.data',
 './topics\\price_amazon_kindle.txt.data',
 './topics\\price_holiday_inn_london.txt.data',
 './topics\\quality_toyota_camry_2007.txt.data',
 './topics\\rooms_bestwestern_hotel_sfo.txt.data',
 './topics\\rooms_swissotel_chicago.txt.data',
 './topics\\room_holiday_inn_london.txt.data',
 './topics\\satellite_garmin_nuvi_255W_gps.txt.data',
 './topics\\screen_garmin_nuvi_255W_gps.txt.data',
 './topics\\screen_ipod_nano_8gb.txt.data',
 './topics\\screen_netbook_1005ha.txt.data',
 './topics\\seats_honda_accord_2008.txt.data',
 './topics\\service_bestwestern_hotel_sfo.txt.data',
 './topics\\service_holiday_inn_london.txt.data',
 './topics\\service_swissotel_hotel_chicago.txt.data',
 './topics\\size_asus_netbook_1005ha.txt.data',
 './topics\\sound_ipod_nano_8gb.txt.data',
 './topics\\speed_garmin_nuvi_255W_gps.txt.data',
 './topics\\speed_windows7.txt.data',
 './topics\\staff_bestwestern_hotel_sfo.txt.data',
 './topics\\staff_swissotel_chicago.txt.data',
 './topics\\transmission_toyota_camry_2007.txt.data',
 './topics\\updates_garmin_nuvi_255W_gps.txt.data',
 './topics\\video_ipod_nano_8gb.txt.data',
 './topics\\voice_garmin_nuvi_255W_gps.txt.data']

In [ ]:
# 파일명과 리뷰 꺼내서 저장, 텍스트, 이미지 파일 처리할때 유용할끄야!!! 기억해~~~ 
filename_list = [] # 파일명 저장
opinion_text  = [] # 리뷰를 저장하는 리스트 

for file_ in all_files:
    # 개별 파일을 읽어서 DataFrame으로 생성 
    df = pd.read_table(file_, index_col=None, header=0, encoding='latin1') # english인 경우 latin1 
    
    # 파일명 추축 (레이블이니까)
    # filename_ = file_.split('\\')[-1] # window용, Mac = '/' # './topics\\voice_garmin_nuvi_255W_gps.txt.data' => voice_garmin_nuvi_255W_gps.txt.data 만 추출
    # filename = filename_.split('.')[0] # voice_garmin_nuvi_255W_gps.txt.data 에서 voice_garmin_nuvi_255W_gps
    filename = file_.split('\\')[-1].split('.')[0]

    filename_list.append(filename)
    opinion_text.append(df.to_string()) # 모든 내용을 컬럼명 포함 모두 문자로 만들어줌

# 파일명 리스트와 파일 내용 리스트를  DataFrame으로 생성
document_df = pd.DataFrame({
    'filename':     filename_list, # label이 됨
    'opinion_text': opinion_text
})
document_df.head()

,filename,opinion_text
0,accuracy_garmin_nuvi_255W_gps,", and is very, very accurate .\n0 but for the most part, we find that the Garmin software provides accurate directions, whereever we intend to go .\n1 This functi..."
1,bathroom_bestwestern_hotel_sfo,"The room was not overly big, but clean and very comfortable beds, a great shower and very clean bathrooms .\n0 The second room was smaller, with a very inconvenient bathroom layout, but at least it was quieter and we were able to sleep .\n1 ..."
2,battery-life_amazon_kindle,"After I plugged it in to my USB hub on my computer to charge the battery the charging cord design is very clever !\n0 After you have paged tru a 500, page book one, page, at, a, time to get from Chapter 2 to Chapter 15, see how excited you are about a low battery and all the time it took to get there !\n1 ..."
3,battery-life_ipod_nano_8gb,short battery life I moved up from an 8gb .\n0 I love this ipod except for the battery life .\n1 ...
4,battery-life_netbook_1005ha,"6GHz 533FSB cpu, glossy display, 3, Cell 23Wh Li, ion Battery , and a 1 .\n0 Not to mention that as of now..."

In [ ]:
# data_list = []

# for file_ in all_files:
#     # 1. 파일 경로에서 파일명(레이블) 추출
#     # os.path.basename을 사용해 OS 호환성 확보
#     filename = os.path.basename(file_).split('.')[0] 

#     # 2. 파이썬 기본 open() 함수로 파일 내용 전체를 읽기
#     # encoding='latin1' 유지
#     try:
#         with open(file_, 'r', encoding='latin1') as f:
#             text_content = f.read() # 파일 내용 전체를 하나의 문자열로 저장
            
#         # 3. 딕셔너리 형태로 리스트에 추가
#         data_list.append({
#             'filename': filename,
#             'opinion_text': text_content
#         })
        
#     except FileNotFoundError:
#         print(f"Error: {file_} not found.")
#     except Exception as e:
#         print(f"An error occurred reading {file_}: {e}")

# # 반복문 종료 후 한 번에 DataFrame 생성
# document_df = pd.DataFrame(data_list)

# print(document_df.head())
# print(document_df['opinion_text'][0][:200]) # 처음 200자 출력 예시

In [ ]:
# # 확인용 코드
# df = pd.read_table(all_files[0], index_col=None, header=0, encoding='latin1') # english인 경우 latin1 
# # df.head()
# df.to_string()

"                                                                                                                                                                                                                                                               , and is very, very accurate .\n0                                                                                                                                                                           but for the most part, we find that the Garmin software provides accurate directions, whereever we intend to go .\n1                                                                                                              This function is not accurate if you don't leave it in battery mode say, when you stop at the Cracker Barrell for lunch and to play one of those trangle games with the tees .\n2                                                                                                                                                                      It provides immediate alternatives if the route from the online map program was inaccurate or blocked by an obstacle .\n3                                                                                                                                                                    I've used other GPS units, as well as GPS built into cars   and to this day NOTHING beats the accuracy of a Garmin GPS .\n4                                                                                                                                                                                                                            It got me from point A to point B with 100% accuracy everytime .\n5                                                                                                                                                                                                                        It has yet to disappoint, getting me everywhere with 100% accuracy .\n6                                                                                                                                                                                                                                   0 out of 5 stars Honest, accurate review, , PLEASE READ !\n7                                                                                                                                                                                                                  Aside from that, every destination I've thrown at has been 100% accurate .\n8                                                                                                                                                                                       In closing, this is a fantastic GPS with some very nice features and is very accurate in directions .\n9                                                                                                                                                                                             Plus, I've always heard that there are  quirks  with any GPS being accurate, having POIs, etc .\n10                                                                                                                                                                                                                                          DESTINATION TIME, , This is pretty accurate too .\n11                                                                                                                                                                                                                                                           But, it's always very accurate .\n12                                                                                                                                                                                                               The map is pretty accurate and the Point of interest database also is good .\n13                                                                                                                                                                                                                                           Most of the times, this info was very accurate .\n14                                                                                                                                                                                                          I've even used it in the  pedestrian  mode, and it's amazing how accurate it is .\n15                                                                                                                                                                                                                      ONLY  is only accurate when an ad says,  Top sirloin steak, ONLY $1 .\n16                                                                                                                                                                                The most accurate review stated that these machines are adjunct to a good map and signs on the interstate .\n17                                                                                                                                                                                                                                         The directions are highly accurate down to a  T  .\n18                                                                                                                                   Depending on what you are using it for, it is a nice adjunct to a travel trip and the directions are accurate and usually the quickest, but not always .\n19                                                                                                                                                                                                      The screen is easy to see, the voice tells you where you are and it's very accurate .\n20                                                                                                                                                                                                                   It was accurate to the minute when it told me when I would arrive home .\n21                                                                                                                                                                                                            0 out of 5 stars GPS Navigator doesn't navigate accurately on a straight road .\n22                                                                                                                                                                                          I was familiar with the streets and only used the Nuvi to get an accurate arrival time estimate .\n23                                                                                                                                                                                                                                 but after that it is very easy and quite accurate to use .\n24                                                                                                                                                                                                                                                  The accuracy at this point is very good .\n25                                                                                                                                              While the 255W routing seems generally accurate and logical, on my first use I discovered that it does have some errors in its internal map .\n26                                                                                                                                                                                                    Bottom line is I wanted a unit that is accurate and had reliable satellite connection .\n27                                                                                                                                                                                                                            I've used it around town and find it to be extremely accurate .\n28                                                                                                                                                                          I found the maps to be inaccurate at first, but after I updated them from Garmin's website everything is golden .\n29                                                                                                                                                                                                                                 A lot of my friends' addresses are inaccurate by any GPS .\n30                                                                                                                                                                                        It loads quickly, have pretty accurate directions, and can recalculate quickly when I miss a turn .\n31                                                                                                                            Because the accuracy is good to the street address level, it may not be able to guide you to the exact location if your destination is inside a shopping mall .\n32                                                                                                                                                                                            I updated to the latest 2010 map soon after I received the unit, so the map is accurate to me .\n33                                                                                                                                                                                                                   I was blown away at the accuracy and routing capability this thing had .\n34   I used it the day I bought it,   and then this morning, and as soon as it comes on it is  ready to navigate  The only downfall of this product, and the only reason I did not give it 5 stars is the fact that the speed limit it displays for the road you are on isn't 100% accurate .\n35                                                                                                                                                                                                        If your looking for a nice, accurate GPS for not so much money, got with this one .\n36                                                                                                                                                                                                                 0 out of 5 stars Inexpensive, accurate, plenty of features, August 6, 2009\n37                                                                                                     The only glitch I have found so far is that the speed limits are not 100% accurate, although the GPS, amazingly, is able to very accurately tell you how fast your vehicle is moving .\n38                                                                I was a little disappointed in the inaccuracy of the posted speed limit, as I'm guilty of not paying close enough attention to those signs, especially w  interstate speed traps that are constantly changing up and down .\n39                                                                                                                                                                                                    The closest one that gives the most accurate route that I usually take is the Navigon .\n40                                                                                                                          After 2 weeks, it has yet to make a mistake, and is always completely accurate ,  even to the point of telling me which side of the street my destination is on .\n41                                                                                                                                                                                                    It has worked well for local driving giving accurate directions for roads and streets .\n42                                                                                                                                                                                                  The estimated time to arrival does not seem to calculate the travelling time accurately .\n43                                                                                                                          Accuracy is as good as any other unit, they all sometimes tell you you have arrived when you haven't, or continue to tell you to turn when you're already there .\n44                                                                                                                                                                                                                                                       Accuracy is determined by the maps .\n45                                                                                                                                                                                                                               Less traveled rural roads will not be accurate on any unit .\n46                                                                                                                                                                                                                                                           Accuracy is within a few yards .\n47                                                                                                                          What the 255w does best is find a street address, business, point of interest, hospital or airport and give you turn, by, turn directions with amazing accuracy .\n48                                                                                                                                                                                    The Garmin is loaded with very accurate maps that generally know the roads in even the remotest areas .\n49                                                        I'm really glad I bought it though, and like the easy to read graphics, the voice used to tell you the name of the street you are to turn on, the uncannily accurate estimates of mileage and time of arrival at your destination .\n50                                                                                                                                                       My new Garmin 255w had very Easy Set Up, Accurate Directions to locations, User Friendly Unit to anyone in my vehicle who tried it .\n51                                                                                                                                 I had a GPS 10, years ago when I owned a boat that was difficult to use and with very poor accuracy so I had assumed that the road GPS wasn't any better .\n52                                                                                                                                                                                            Practiced visiting places I already knew to see how accurate the directions and maps would be .\n53                                                                                                                                                                                                                            Easy to use, excellent accuracy, nice and intuitive interface .\n54                                                                                                                                                                                                                            The directions provided have all been quite accurate thus far .\n55                                                                                                                                                                                                             ,  Very Accurate but with one small glitch I found ,  I'll explain in the CONS\n56                                                                                                                                                                                                                      This is a great GPS, it is so easy to use and it is always accurate .\n57                                                                                                                                        Very easy to operate and pretty accurate as well, only led me astray once and that was in northern Maine where roads are few and paved ones fewer .\n58                                                                                                                                                                                                                                      Easy to use and amazed at how accurate this item is .\n59                                                                                                                                                                                                                                        To date it's been a very easy to use and accurate .\n60                                                                                                                                                                                                                                         Mounted really easily and has been very accurate .\n61                                                                                                                                                                                                                                                              seems to be rather accurate .\n62                                                                                                                                                                                                        It was accurate on determing original directions and recalculating when necessary .\n63                                                                                                                                                                                                                                                          Highly accurate, POIs are great .\n64                                                                                                                               I can't believe how accurate and detailed the information estimated time of arrival,speed limits along the way,and detailed map of my route, to name a few .\n65                                                                                                                                                                                                                Speed of calculation, accuracy, and simplicity of operation are top notch ."

문서를 TF-IDF 형태로 피처 벡터화하겠습니다. TfidfVectorizer는 Lemmatization(어근 추출) 같은 어근 변환을 직접 지원하진 않지만, 
**tokenizer(단어분리)** 인자에 커스텀 어근 변환 함수를 적용해 어근 변환을 수행할 수 있습니다.  
이를 위해 LemNormalize() 함수를 만들겠습니다(해당 함수는 이전에 설명드린 단어 토큰화, 스톱 워드 제거, 어근 변환에 기반하고 있기에 여기서 언급 드리지 않고, 부록으로 제공되는 소스
코드에서 보다 자세한 설명을 드리고 있으니, 참조 부탁드립니다).  
ngram은 (1,2)로 하고, min_df와 max_df 범위를 설정해 피처의 개수를 제한하겠습니다. 
TfidfVectorizer의 fit_transform()의 인자로 document_df DataFrame의 opinion_text 칼럼을 입력하면 
개별 문서 텍스트에 대해 TF-IDF 변환된 피처 벡터화된 행렬을 구할 수 있습니다.

In [ ]:
# 함수 만들기 : English 처리용
from nltk.stem import WordNetLemmatizer
import nltk
import string

# 제외할 문자 dict 생성
remove_punct_dict = dict((ord(punct), None) for punct in string.punctuation)
# '!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~' ord(puct) => 숫자로 바꾼후 key:value 만든 후 
lemmar = WordNetLemmatizer()

# 입력으로 들어온 token단어들에 대해서 lemmatization 어근 변환.
def LemTokens(tokens):
    return [lemmar.lemmatize(token) for token in tokens]


# TfidfVectorizer 객체 생성 시 tokenizer인자로 해당 함수를 설정하여 lemmatization 적용
# 입력으로 문장을 받아서 stop words 제거-> 소문자 변환 -> 단어 토큰화 -> lemmatization 어근 변환.
def LemNormalize(text):
    # 한국어는 nltk 못씀!!!! 왜냐 지원 안혀~ , 글고 어근을 추출하자노.. 우리는 '형태소'인디 
    return LemTokens(nltk.word_tokenize(text.lower().translate(remove_punct_dict))) # word_tokenize(분리하겠다!)
  
# 영어 - 문서안에서 단어를 추출하고 (어근을 추출하고 그걸) 숫자로 변환 , 한그은 어근이 아닌 형태소!!! 이 코드는 한국어에 적용 불가

In [ ]:
##  한국어 처리! 프로젝트에 써라! AIHUB 이용하라 ######################################
from konlpy.tag import Okt # konlpy 설치해야 함!!!!
import re

# Okt 객체 생성 (트위터 형태소 분석기)
okt = Okt()

# 1. 토큰화 및 어간(형태소) 추출 (Lemmatization 대응)
def KoTokens(text):
    # stem=True : 동사/형용사를 원형으로 변환 (예: '합니다' -> '하다', '예쁜' -> '예쁘다')
    # norm=True : 오타나 SNS 스타일 문체를 정제 (예: '안뇽' -> '안녕')
    return okt.morphs(text, stem=True, norm=True)

# 2. 전처리 및 토큰화 통합 함수 (LemNormalize 대응)
def KoNormalize(text):
    # 정규표현식을 이용한 특수문자 제거 (한글, 영문, 숫자, 공백만 남김)
    # string.punctuation을 쓰는 것보다 한글 텍스트 정제에 더 효과적입니다.
    text = re.sub(r'[^가-힣a-zA-Z0-9\s]', '', text)
    
    # 영어가 섞여 있을 경우를 위해 소문자 변환
    text = text.lower()
    
    # 형태소 분석 및 리스트 반환
    return KoTokens(text)

# --- 테스트 실행 ---
sample_text = "아버지가 방에 들어가신다! (Father enters the room.) 웃고 계십니다."
result = KoNormalize(sample_text)

print(f"원본: {sample_text}")
print(f"결과: {result}")

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

# tokenizer에 위에서 정의한 KoNormalize 함수 지정
tfidf_vect = TfidfVectorizer(tokenizer=KoNormalize, min_df=1)

# 예시 데이터 학습
sentences = ['아버지가 방에 들어가신다.', '어머니는 부엌에서 요리하신다.']
tfidf_matrix = tfidf_vect.fit_transform(sentences)

print(tfidf_vect.get_feature_names_out())
# 출력 예시: ['가다', '나다', '방', '부엌', '아버지', '어머니', '에', '에서', '요리', '하다']
# (조사와 어간이 분리되고 기본형으로 바뀐 것을 확인할 수 있습니다)

In [ ]:
import string
string.punctuation # '!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~' 야들 전부 삭제할때 유용하지만 요즘은 지우면 안돼!!!

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [8]:
# F-IDF 기반 Vectorization 적용 및 KMeans 군집화 수행
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf_vect = TfidfVectorizer(tokenizer=LemNormalize, stop_words='english' , \
                             ngram_range=(1,2), min_df=0.05, max_df=0.85 )

#opinion_text 컬럼값으로 feature vectorization 수행
feature_vect = tfidf_vect.fit_transform(document_df['opinion_text'])

In [9]:
# 군집화 하자! 센터를 찾을꺼다
from sklearn.cluster import KMeans

# 5개 집합으로 군집화 수행. 예제를 위해 동일한 클러스터링 결과 도출용 random_state=0 
km_cluster = KMeans(n_clusters=5, max_iter=10000, random_state=0)
km_cluster.fit(feature_vect)
cluster_label = km_cluster.labels_
cluster_centers = km_cluster.cluster_centers_

In [ ]:
document_df['cluster_label'] = cluster_label
document_df.head()
## DBSCAN 돌리면 관련없는애들 좀 더 거를 수 있을 지도?

,filename,opinion_text,cluster_label
0,accuracy_garmin_nuvi_255W_gps,", and is very, very accurate .\n0 but for the most part, we find that the Garmin software provides accurate directions, whereever we intend to go .\n1 This functi...",2
1,bathroom_bestwestern_hotel_sfo,"The room was not overly big, but clean and very comfortable beds, a great shower and very clean bathrooms .\n0 The second room was smaller, with a very inconvenient bathroom layout, but at least it was quieter and we were able to sleep .\n1 ...",1
2,battery-life_amazon_kindle,"After I plugged it in to my USB hub on my computer to charge the battery the charging cord design is very clever !\n0 After you have paged tru a 500, page book one, page, at, a, time to get from Chapter 2 to Chapter 15, see how excited you are about a low battery and all the time it took to get there !\n1 ...",4
3,battery-life_ipod_nano_8gb,short battery life I moved up from an 8gb .\n0 I love this ipod except for the battery life .\n1 ...,4
4,battery-life_netbook_1005ha,"6GHz 533FSB cpu, glossy display, 3, Cell 23Wh Li, ion Battery , and a 1 .\n0 Not to mention that as of now...",4

In [ ]:
document_df[document_df['cluster_label']==0].sort_values(by='filename') # 아마존킨들 관련

,filename,opinion_text,cluster_label
5,buttons_amazon_kindle,"I thought it would be fitting to christen my Kindle with the Stephen King novella UR, so went to the Amazon site on my computer and clicked on the button to buy it .\n0 As soon as I'd clicked the button to confirm my order it appeared on my Kindle almost immediately !\n1 ...",0
10,eyesight-issues_amazon_kindle,"It feels as easy to read as the K1 but doesn't seem any crisper to my eyes .\n0 the white is really GREY, and to avoid considerable eye, strain I had to refresh pages every other page .\n1 The dream has always been a portable electronic device that could hold a ton of reading material, automate subscriptions and fa...",0
12,fonts_amazon_kindle,"Being able to change the font sizes is awesome !\n0 For whatever reason, Amazon decided to make the Font on the Home Screen ...",0
23,navigation_amazon_kindle,"In fact, the entire navigation structure has been completely revised , I'm still getting used to it but it's a huge step forward .\n0 ...",0
27,price_amazon_kindle,"If a case was included, as with the Kindle 1, that would have been reflected in a higher price .\n0 lower overall price, with nice leather cover .\n1 ...",0
28,price_holiday_inn_london,"All in all, a normal chain hotel on a nice location , I will be back if I do not find anthing closer to Picadilly for a better price .\n0 ...",0

In [ ]:
document_df[document_df['cluster_label']==1].sort_values(by='filename') # 호텔관련

,filename,opinion_text,cluster_label
1,bathroom_bestwestern_hotel_sfo,"The room was not overly big, but clean and very comfortable beds, a great shower and very clean bathrooms .\n0 The second room was smaller, with a very inconvenient bathroom layout, but at least it was quieter and we were able to sleep .\n1 ...",1
13,food_holiday_inn_london,The room was packed to capacity with queues at the food buffets .\n0 The over zealous staff cleared our unfinished drinks while we were collecting cooked food and movement around the room with plates was difficult in the crowded circumstances .\n1 ...,1
14,food_swissotel_chicago,The food for our event was delicious .\n0 ...,1
15,free_bestwestern_hotel_sfo,The wine reception is a great idea as it is nice to meet other travellers and great having access to the free Internet access in our room .\n0 They also have a computer available with free internet which is a nice bonus but I didn't find that out till the day before we left but was still able to get on there to check our flight to Vegas the next day .\n1 ...,1
20,location_bestwestern_hotel_sfo,"Good Value good location , ideal choice .\n0 Great Location , Nice Rooms , Helpless Concierge\n1 ...",1
21,location_holiday_inn_london,"Great location for tube and we crammed in a fair amount of sightseeing in a short time .\n0 All in all, a normal chain hotel on a nice lo...",1
24,parking_bestwestern_hotel_sfo,Parking was expensive but I think this is common for San Fran .\n0 there is a fee for parking but well worth it seeing no where to park if you do have a car .\n1 ...,1
32,room_holiday_inn_london,"We arrived at 23,30 hours and they could not recommend a restaurant so we decided to go to Tesco, with very limited choices but when you are hingry you do not careNext day they rang the bell at 8,00 hours to clean the room, not being very nice being waken up so earlyEvery day they gave u...",1
30,rooms_bestwestern_hotel_sfo,"Great Location , Nice Rooms , H...",1
31,rooms_swissotel_chicago,"The Swissotel is one of our favorite hotels in Chicago and the corner rooms have the most fantastic views in the city .\n0 The rooms look like they were just remodled and upgraded, there was an HD TV and a nice iHome docking station to put my iPod so I could set the alarm to wake up with my music instead of the radio .\n1 ...",1
38,service_bestwestern_hotel_sfo,"Both of us having worked in tourism for over 14 years were very disappointed at the level of service provided by this gentleman .\n0 The service was good, very friendly staff and we loved the free wine reception each night .\n1 ...",1
39,service_holiday_inn_london,"not customer, oriented hotelvery low service levelboor reception\n0 The room was quiet, clean, the bed and pillows were comfortable, and the serv...",1
40,service_swissotel_hotel_chicago,Mediocre room and service for a very extravagant price .\n0 ...,1
45,staff_bestwestern_hotel_sfo,Staff are friendl...,1
46,staff_swissotel_chicago,"The staff at Swissotel were not particularly nice .\n0 Each time I waited at the counter for staff for several minutes and then was waved to the desk upon my turn with no hello or anything, or apology for waiting in line .\n1 ...",1

In [ ]:
document_df[document_df['cluster_label']==2].sort_values(by='filename') # 전자제품?

,filename,opinion_text,cluster_label
0,accuracy_garmin_nuvi_255W_gps,", and is very, very accurate .\n0 but for the most part, we find that the Garmin software provides accurate directions, whereever we intend to go .\n1 This functi...",2
8,directions_garmin_nuvi_255W_gps,You also get upscale features like spoken directions including street names and programmable POIs .\n0 I used to hesitate to go out of my directions but no...,2
9,display_garmin_nuvi_255W_gps,"3 quot widescreen display was a bonus .\n0 This made for smoother graphics on the 255w of the vehicle moving along displayed roads, where the 750's display was more of a jerky movement .\n1 ...",2
19,keyboard_netbook_1005ha,", I think the new keyboard rivals the great hp mini keyboards .\n0 Since the battery life difference is minimum, the only reason to upgrade would be to get the better keyboard .\n1 The keyboard is now as good as t...",2
33,satellite_garmin_nuvi_255W_gps,"It's fast to acquire satellites .\n0 If you've ever had a Brand X GPS take you on some strange route that adds 20 minutes to your trip, has you turn the wrong way down a one way road, tell you to turn AFTER you've passed the street, frequently loses the satellite signal, or has old maps missing streets, you know how important this stuff is .\n1 ...",2
34,screen_garmin_nuvi_255W_gps,It is easy to read and when touching the screen it works great !\n0 and zoom out buttons on the 255w to the same side of the screen which makes it a bit easier .\n1 ...,2
35,screen_ipod_nano_8gb,"As always, the video screen is sharp and bright .\n0 2, inch screen and a glossy, polished aluminum finish that one CNET editor described as looking like a Christmas tree ornament .\n1 ...",2
36,screen_netbook_1005ha,Keep in mind that once you get in a room full of light or step outdoors screen reflections could become annoying .\n0 I've used mine outsi...,2
41,size_asus_netbook_1005ha,"A few other things I'd like to point out is that you must push the micro, sized right angle end of the ac adapter until it snaps in place or the battery may not charge .\n0 The full size right shift k...",2
43,speed_garmin_nuvi_255W_gps,Another feature on the 255w is a display of the posted speed limit on the road which you are currently on right above your current displayed speed .\n0 I found myself not even looking at my car speedometer as I could easily see my current speed and the speed limit of my route at a glance .\n1 ...,2
48,updates_garmin_nuvi_255W_gps,"Another thing to consider was that I paid $50 less for the 750 and it came with the FM transmitter cable and a USB cord to connect it to your computer for updates and downloads .\n0 update and reroute much _more_ quickly than my other GPS .\n1 UPDATE ON THIS , It finally turned out that to see the elevation contours at lowe...",2
50,voice_garmin_nuvi_255W_gps,The voice prompts and maps are wonderful especially when driving after dark .\n0 I also thought the the voice prompts of the 750 where more pleasant sounding than the 255w's .\n1 ...,2

In [ ]:
from sklearn.cluster import KMeans

# 3개의 집합으로 군집화 ! 제대로 안됐다! 군집화 개수가 중요하다!!!
km_cluster = KMeans(n_clusters=3, max_iter=10000, random_state=0)
km_cluster.fit(feature_vect)
cluster_label = km_cluster.labels_

# 소속 클러스터를 cluster_label 컬럼으로 할당하고 cluster_label 값으로 정렬
document_df['cluster_label'] = cluster_label
document_df.sort_values(by='cluster_label')

,filename,opinion_text,cluster_label
5,buttons_amazon_kindle,"I thought it would be fitting to christen my Kindle with the Stephen King novella UR, so went to the Amazon site on my computer and clicked on the button to buy it .\n0 As soon as I'd clicked the button to confirm my order it appeared on my Kindle almost immediately !\n1 ...",0
10,eyesight-issues_amazon_kindle,"It feels as easy to read as the K1 but doesn't seem any crisper to my eyes .\n0 the white is really GREY, and to avoid considerable eye, strain I had to refresh pages every other page .\n1 The dream has always been a portable electronic device that could hold a ton of reading material, automate subscriptions and fa...",0
12,fonts_amazon_kindle,"Being able to change the font sizes is awesome !\n0 For whatever reason, Amazon decided to make the Font on the Home Screen ...",0
27,price_amazon_kindle,"If a case was included, as with the Kindle 1, that would have been reflected in a higher price .\n0 lower overall price, with nice leather cover .\n1 ...",0
25,performance_honda_accord_2008,"Very happy with my 08 Accord, performance is quite adequate it has nice looks and is a great long, distance cruiser .\n0 6, 4, 3 eco engine has poor performance and gas mileage of 22 highway .\n1 Overall performance is good but comfort level is poor .\n2 ...",0
22,mileage_honda_accord_2008,"It's quiet, get good gas mileage and looks clean inside and out .\n0 The mileage is great, and I've had to get used to stopping less for gas .\n1 Thought gas ...",0
23,navigation_amazon_kindle,"In fact, the entire navigation structure has been completely revised , I'm still getting used to it but it's a huge step forward .\n0 ...",0
16,gas_mileage_toyota_camry_2007,Ride seems comfortable and gas mileage fairly good averaging 26 city and 30 open road .\n0 ...,0
29,quality_toyota_camry_2007,I previously owned a Toyota 4Runner which had incredible build quality and reliability .\n0 I bought the Camry because of Toyota reliability and qua...,0
44,speed_windows7,"Windows 7 is quite simply faster, more stable, boots faster, goes to sleep faster, comes back from sleep faster, manages your files better and on top of that it's beautiful to look at and easy to use .\n0 , faster about 20% to 30% faster at running applications than my Vista , seriously\n1 ...",0
15,free_bestwestern_hotel_sfo,The wine reception is a great idea as it is nice to meet other travellers and great having access to the free Internet access in our room .\n0 They also have a computer available with free internet which is a nice bonus but I didn't find that out till the day before we left but was still able to get on there to check our flight to Vegas the next day .\n1 ...,1
21,location_holiday_inn_london,"Great location for tube and we crammed in a fair amount of sightseeing in a short time .\n0 All in all, a normal chain hotel on a nice lo...",1
14,food_swissotel_chicago,The food for our event was delicious .\n0 ...,1
13,food_holiday_inn_london,The room was packed to capacity with queues at the food buffets .\n0 The over zealous staff cleared our unfinished drinks while we were collecting cooked food and movement around the room with plates was difficult in the crowded circumstances .\n1 ...,1
6,comfort_honda_accord_2008,"Drivers seat not comfortable, the car itself compared to other models of similar class .\n0 ...",1
1,bathroom_bestwestern_hotel_sfo,"The room was not overly big, but clean and very comfortable beds, a great shower and very clean bathrooms .\n0 The second room was smaller, with a very inconvenient bathroom layout, but at least it was quieter and we were able to sleep .\n1 ...",1
30,rooms_bestwestern_hotel_sfo,"Great Location , Nice Rooms , H...",1
20,location_bestwestern_hotel_sfo,"Good Value good location , ideal choice .\n0 Great Location , Nice Rooms , Helpless Concierge\n1 ...",1
18,interior_toyota_camry_2007,"First of all, the interior has way too many cheap plastic parts like the cheap plastic center piece that houses the clock .\n0 3 blown struts at 30,000 miles, interior trim coming loose and rattling squeaking, stains on paint, and bug splats taking paint off, premature uneven brake wear, on 3rd windsh...",1
24,parking_bestwestern_hotel_sfo,Parking was expensive but I think this is common for San Fran .\n0 there is a fee for parking but well worth it seeing no where to park if you do have a car .\n1 ...,1
31,rooms_swissotel_chicago,"The Swissotel is one of our favorite hotels in Chicago and the corner rooms have the most fantastic views in the city .\n0 The rooms look like they were just remodled and upgraded, there was an HD TV and a nice iHome docking station to put my iPod so I could set the alarm to wake up with my music instead of the radio .\n1 ...",1
28,price_holiday_inn_london,"All in all, a normal chain hotel on a nice location , I will be back if I do not find anthing closer to Picadilly for a better price .\n0 ...",1
17,interior_honda_accord_2008,I love the new body style and the interior is a simple pleasure except for the center dash .\n0 ...,1
7,comfort_toyota_camry_2007,"Ride seems comfortable and gas mileage fairly good averaging 26 city and 30 open road .\n0 Seats are fine, in fact of all the smaller sedans this is the most comfortable I found for the price as I am 6', 2 and 250# .\n1 Great gas mileage and comfortable on long trips ...",1
37,seats_honda_accord_2008,"Front seats are very uncomfortable .\n0 No memory seats, no trip computer, can only display outside temp with trip odometer .\n1 ...",1
40,service_swissotel_hotel_chicago,Mediocre room and service for a very extravagant price .\n0 ...,1
45,staff_bestwestern_hotel_sfo,Staff are friendl...,1
46,staff_swissotel_chicago,"The staff at Swissotel were not particularly nice .\n0 Each time I waited at the counter for staff for several minutes and then was waved to the desk upon my turn with no hello or anything, or apology for waiting in line .\n1 ...",1
39,service_holiday_inn_london,"not customer, oriented hotelvery low service levelboor reception\n0 The room was quiet, clean, the bed and pillows were comfortable, and the serv...",1
38,service_bestwestern_hotel_sfo,"Both of us having worked in tourism for over 14 years were very disappointed at the level of service provided by this gentleman .\n0 The service was good, very friendly staff and we loved the free wine reception each night .\n1 ...",1
32,room_holiday_inn_london,"We arrived at 23,30 hours and they could not recommend a restaurant so we decided to go to Tesco, with very limited choices but when you are hingry you do not careNext day they rang the bell at 8,00 hours to clean the room, not being very nice being waken up so earlyEvery day they gave u...",1
0,accuracy_garmin_nuvi_255W_gps,", and is very, very accurate .\n0 but for the most part, we find that the Garmin software provides accurate directions, whereever we intend to go .\n1 This functi...",2
26,performance_netbook_1005ha,"The Eee Super Hybrid Engine utility lets users overclock or underclock their Eee PC's to boost performance or provide better battery life depending on their immediate requirements .\n0 In Super Performance mode CPU, Z shows the bus speed to increase up to 169 .\n1 One...",2
19,keyboard_netbook_1005ha,", I think the new keyboard rivals the great hp mini keyboards .\n0 Since the battery life difference is minimum, the only reason to upgrade would be to get the better keyboard .\n1 The keyboard is now as good as t...",2
2,battery-life_amazon_kindle,"After I plugged it in to my USB hub on my computer to charge the battery the charging cord design is very clever !\n0 After you have paged tru a 500, page book one, page, at, a, time to get from Chapter 2 to Chapter 15, see how excited you are about a low battery and all the time it took to get there !\n1 ...",2
3,battery-life_ipod_nano_8gb,short battery life I moved up from an 8gb .\n0 I love this ipod except for the battery life .\n1 ...,2
4,battery-life_netbook_1005ha,"6GHz 533FSB cpu, glossy display, 3, Cell 23Wh Li, ion Battery , and a 1 .\n0 Not to mention that as of now...",2
11,features_windows7,"I had to uninstall anti, virus and selected other programs, some of which did not have listings in the Programs and Features Control Panel section .\n0 This review briefly touches upon some of the key features and enhancements of Microsoft's latest OS .\n1 ...",2
8,directions_garmin_nuvi_255W_gps,You also get upscale features like spoken directions including street names and programmable POIs .\n0 I used to hesitate to go out of my directions but no...,2
9,display_garmin_nuvi_255W_gps,"3 quot widescreen display was a bonus .\n0 This made for smoother graphics on the 255w of the vehicle moving along displayed roads, where the 750's display was more of a jerky movement .\n1 ...",2
36,screen_netbook_1005ha,Keep in mind that once you get in a room full of light or step outdoors screen reflections could become annoying .\n0 I've used mine outsi...,2
33,satellite_garmin_nuvi_255W_gps,"It's fast to acquire satellites .\n0 If you've ever had a Brand X GPS take you on some strange route that adds 20 minutes to your trip, has you turn the wrong way down a one way road, tell you to turn AFTER you've passed the street, frequently loses the satellite signal, or has old maps missing streets, you know how important this stuff is .\n1 ...",2
34,screen_garmin_nuvi_255W_gps,It is easy to read and when touching the screen it works great !\n0 and zoom out buttons on the 255w to the same side of the screen which makes it a bit easier .\n1 ...,2
35,screen_ipod_nano_8gb,"As always, the video screen is sharp and bright .\n0 2, inch screen and a glossy, polished aluminum finish that one CNET editor described as looking like a Christmas tree ornament .\n1 ...",2
43,speed_garmin_nuvi_255W_gps,Another feature on the 255w is a display of the posted speed limit on the road which you are currently on right above your current displayed speed .\n0 I found myself not even looking at my car speedometer as I could easily see my current speed and the speed limit of my route at a glance .\n1 ...,2
42,sound_ipod_nano_8gb,headphone jack i got a clear case for it and it i got a clear case for it and it like prvents me from being able to put the jack all the way in so the sound can b messsed up or i can get it in there and its playing well them go to move or something and it slides out .\n0 Picture and sound quality are excellent for this typ of devic .\n1 ...,2
41,size_asus_netbook_1005ha,"A few other things I'd like to point out is that you must push the micro, sized right angle end of the ac adapter until it snaps in place or the battery may not charge .\n0 The full size right shift k...",2
47,transmission_toyota_camry_2007,"After slowing down, transmission has to be kicked to speed up .\n0 ...",2
48,updates_garmin_nuvi_255W_gps,"Another thing to consider was that I paid $50 less for the 750 and it came with the FM transmitter cable and a USB cord to connect it to your computer for updates and downloads .\n0 update and reroute much _more_ quickly than my other GPS .\n1 UPDATE ON THIS , It finally turned out that to see the elevation contours at lowe...",2
49,video_ipod_nano_8gb,"I bought the 8, gig Ipod Nano that has the built, in video camera .\n0 Itunes has an on, line store, where you may purchase and download music and videos which will install onto the ipod .\n1 ...",2
50,voice_garmin_nuvi_255W_gps,The voice prompts and maps are wonderful especially when driving after dark .\n0 I also thought the the voice prompts of the 750 where more pleasant sounding than the 255w's .\n1 ...,2

In [ ]:
# 군집(Cluster)별 핵심 단어 추출 - KMeans에서는 센터점에서 가까운 단어들! 많이 쓴다규!!! (거리 기반, 가까울 뿐, 관계성이 없다)
cluster_centers = km_cluster.cluster_centers_ # 중심점 찾아서
print('cluster_centers shape :', cluster_centers.shape) # (3, 4610) 3: 군집수, 4610: 단어수, 축의 수, 차원의 수!!! 차원의 저주!!!
print(cluster_centers)

## 아래 함수들은 좋으니까 프로젝트에서 써라~~~잉

cluster_centers shape : (3, 4610)
[[0.00580396 0.00092552 0.         ... 0.         0.         0.        ]
 [0.         0.00075846 0.00133071 ... 0.         0.00139731 0.00110157]
 [0.00966614 0.         0.         ... 0.0088286  0.         0.        ]]

In [ ]:
# 군집별 top n 핵심단어, 그 단어의 중심 위치 상대값, 대상 파일명들을 반환함. 
def get_cluster_details(cluster_model, cluster_data, feature_names, clusters_num, top_n_features=10):
    cluster_details = {}
    
    # cluster_centers array 의 값이 큰 순으로 정렬된 index 값을 반환
    # 군집 중심점(centroid)별 할당된 word 피처들의 거리값이 큰 순으로 값을 구하기 위함.  
    centroid_feature_ordered_ind = cluster_model.cluster_centers_.argsort()[:,::-1]
    
    # 개별 군집별로 iteration하면서 핵심단어, 그 단어의 중심 위치 상대값, 대상 파일명 입력
    for cluster_num in range(clusters_num):
        # 개별 군집별 정보를 담을 데이터 초기화. 
        cluster_details[cluster_num] = {}
        cluster_details[cluster_num]['cluster'] = cluster_num
        
        # cluster_centers_.argsort()[:,::-1] 로 구한 index 를 이용하여 top n 피처 단어를 구함. 
        top_feature_indexes = centroid_feature_ordered_ind[cluster_num, :top_n_features]
        top_features = [ feature_names[ind] for ind in top_feature_indexes ]
        
        # top_feature_indexes를 이용해 해당 피처 단어의 중심 위치 상댓값 구함 
        top_feature_values = cluster_model.cluster_centers_[cluster_num, top_feature_indexes].tolist()
        
        # cluster_details 딕셔너리 객체에 개별 군집별 핵심 단어와 중심위치 상대값, 그리고 해당 파일명 입력
        cluster_details[cluster_num]['top_features'] = top_features
        cluster_details[cluster_num]['top_features_value'] = top_feature_values
        filenames = cluster_data[cluster_data['cluster_label'] == cluster_num]['filename']
        filenames = filenames.values.tolist()
        cluster_details[cluster_num]['filenames'] = filenames
        
    return cluster_details

In [17]:
def print_cluster_details(cluster_details):
    for cluster_num, cluster_detail in cluster_details.items():
        print('####### Cluster {0}'.format(cluster_num))
        print('Top features:', cluster_detail['top_features'])
        print('Reviews 파일명 :',cluster_detail['filenames'][:7])
        print('==================================================')

In [18]:
feature_names = tfidf_vect.get_feature_names_out()

cluster_details = get_cluster_details(cluster_model=km_cluster, cluster_data=document_df,\
                                  feature_names=feature_names, clusters_num=3, top_n_features=10 )
print_cluster_details(cluster_details)

####### Cluster 0
Top features: ['mileage', 'kindle', 'page', 'gas', 'button', 'gas mileage', 'font', 'performance', 'book', 'eye']
Reviews 파일명 : ['buttons_amazon_kindle', 'eyesight-issues_amazon_kindle', 'fonts_amazon_kindle', 'gas_mileage_toyota_camry_2007', 'mileage_honda_accord_2008', 'navigation_amazon_kindle', 'performance_honda_accord_2008']
==================================================
####### Cluster 1
Top features: ['room', 'hotel', 'service', 'staff', 'interior', 'food', 'location', 'seat', 'comfortable', 'bathroom']
Reviews 파일명 : ['bathroom_bestwestern_hotel_sfo', 'comfort_honda_accord_2008', 'comfort_toyota_camry_2007', 'food_holiday_inn_london', 'food_swissotel_chicago', 'free_bestwestern_hotel_sfo', 'interior_honda_accord_2008']
==================================================
####### Cluster 2
Top features: ['screen', 'battery', 'battery life', 'life', 'keyboard', 'video', 'direction', 'voice', 'map', 'feature']
Reviews 파일명 : ['accuracy_garmin_nuvi_255W_gps', 'battery-life_amazon_kindle', 'battery-life_ipod_nano_8gb', 'battery-life_netbook_1005ha', 'directions_garmin_nuvi_255W_gps', 'display_garmin_nuvi_255W_gps', 'features_windows7']
==================================================

최종적으로 나중에~ graphRAG로 가야한다. 성능이 좋다. (MS사에서 나온걸로 성능이 좋다. LLM이랑 붙을 듯! 많은 산업들의 자동화에 사용될 것 같다)  
RAG 는 vector: 단어를 vector로 만들어 그래프로 만든것. (단어와 단어를 연결해서...) 연결성이 나온다!!!
KMeans 는 거리기반, 가까울 수록 묶어주지만, 관계를 파악할 수 없다. 위에 있는 거가 잘 나온다

## BERTtopic, graphRAG 파이널에서 써봐라!